spring:
    datasource:
        url: jdbc:postgresql://db:5432/jpa_specification
        password: 123
        username: myuser
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                show_sql: true